### ISSUE TITLE
Need a fix

### ISSUE THREAD

**Issue by ghost** [seedjay/video-fragment-sniffer#1]
This is a very useful tool, but,
Everytime i touch the dowload button the response is a new tab with the link.

Can you change a little bit the code to have the response of the download button to be imported directly to IDM and/or Jdownloader ?

Thanks

**Comment by ghost** [comment]
Also you should add extra script to ffmpeg concatenate all the downloaded videos.

Have a great day!!

**Comment by seedjay** [comment]
Hi alfredocesar,

Thank you for your interest in the tool.

Theoretically, F4F files should download automatically when opened in a browser. A new tab would open for just a split second (the time to send the file to the download queue), and it should close right after. If you're being prompted what to do with this file, try in another browser (Chrome doesn't prompt you).

I unfortunately don't plan to integrate JDownloader or IDM at the moment, but feel free to create a pull request should this be something you need. Same for the software to concatenate fragments. This tool was just a starting point for you guys to get creative ;)

Cheers,
Chris
